"""Split known interface and reading glyphs from existing OFL CJK fonts.

Original faces remain as fallbacks for arbitrary user input. Disjoint unicode
ranges keep normal application pages from downloading the entire fallback font.
All inputs are local; generated files contain font glyphs, not game text.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys
import tempfile

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))

FACES = [
    ('Vengeance Sans','zh-Hans','assets/fonts/noto-sans-sc.woff2','100 900'),
    ('Vengeance JP','ja','auth/theme/fonts/noto-jp.woff2','400 500'),
    ('Vengeance JP','ja','auth/theme/fonts/noto-jp-bold.woff2','600 900'),
    ('Vengeance TC','zh-Hant','auth/theme/fonts/noto-tc.woff2','400 500'),
    ('Vengeance TC','zh-Hant','auth/theme/fonts/noto-tc-bold.woff2','600 900'),
    ('Archive Serif SC','zh-Hans','auth/theme/fonts/archive-serif-sc.woff2','600 900'),
    ('Archive Serif JP','ja','auth/theme/fonts/archive-serif-jp.woff2','600 900'),
    ('Archive Serif TC','zh-Hant','auth/theme/fonts/archive-serif-tc.woff2','600 900'),
]


def corpora(web):
    from planner import catalog
    base = catalog()
    result = {}
    chinese_source = ''.join(path.read_text() for path in web.rglob('*')
                             if path.suffix in ('.html','.js') and 'assets' not in path.relative_to(web).parts)
    for language in ('zh-Hans','ja','zh-Hant'):
        interface = json.loads((web/'auth/theme/locales'/('en.json' if language=='zh-Hans' else language+'.json')).read_text())
        parts = list(interface) if language=='zh-Hans' else list(interface.values())
        # Shared markup is briefly visible before localization completes. Its
        # labels and punctuation must not fetch an entire reading subset.
        parts.append(chinese_source)
        if language=='zh-Hans':
            full = json.dumps(base,ensure_ascii=False)
            for kind in ('demons','skills','essences','innateSkills'):
                for item in base[kind]:
                    parts.extend(str(item.get(key,'')) for key in ('label','raceLabel','effectZh','costZh'))
        else:
            game_path = web/'assets/locales'/(language+'.json')
            game = json.loads(game_path.read_text()) if game_path.is_file() else {}
            full = json.dumps(game,ensure_ascii=False)
            parts.extend(game.get('races',{}).values())
            for kind in ('demons','skills','essences'):
                for item in game.get(kind,{}).values():
                    parts.extend(str(item.get(key,'')) for key in ('name','effect','cost'))
        core = set(map(ord,''.join(parts)))
        result[language] = (core, core | set(map(ord,full)))
    return result


def unicode_ranges(points):
    ranges = []
    for point in sorted(points):
        if ranges and ranges[-1][1]+1 == point:
            ranges[-1][1] = point
        else:
            ranges.append([point,point])
    return ','.join(f'U+{first:X}' if first==last else f'U+{first:X}-{last:X}' for first,last in ranges)


def face_rule(family, relative, weight, points):
    return f"@font-face {{ font-family:'{family}'; src:url('/{relative}') format('woff2'); font-style:normal; font-weight:{weight}; font-display:swap; unicode-range:{unicode_ranges(points)}; }}"


def build(web):
    output = web/'auth/theme/fonts/optimized'
    output.mkdir(parents=True,exist_ok=True)
    characters = corpora(web)
    css = ['/* Generated by scripts/build_font_subsets.py. Fonts retain their original OFL licenses. */']
    report = []
    for family,language,relative,weight in FACES:
        source = web/relative
        font = TTFont(source)
        available = set(font.getBestCmap())
        font.close()
        core,reading = characters[language]
        groups = [core & available, (reading-core) & available]
        if len(groups[0]) >= len(available)*0.9:
            css.append(face_rule(family,relative,weight,available))
            report.append({'family':family,'source':relative,'retainedOriginal':True})
            continue
        original = source.read_bytes()
        for index,points in enumerate(groups):
            if not points:
                continue
            selection = ','.join(map(str,sorted(points)))
            digest = hashlib.sha256(original+selection.encode()+b'font-subset-v1').hexdigest()[:12]
            destination = output/f'{source.stem}-{digest}-{index}.woff2'
            if not destination.is_file():
                options = subset.Options()
                options.name_IDs = ['*']
                options.name_legacy = True
                options.name_languages = ['*']
                options.layout_features = ['*']
                font = TTFont(source,recalcTimestamp=False)
                worker = subset.Subsetter(options=options)
                worker.populate(unicodes=points)
                worker.subset(font)
                font.flavor = 'woff2'
                with tempfile.NamedTemporaryFile(dir=output,prefix='.font-',delete=False) as temporary:
                    temporary_path = Path(temporary.name)
                try:
                    font.save(temporary_path)
                    temporary_path.replace(destination)
                finally:
                    font.close()
                    temporary_path.unlink(missing_ok=True)
            with TTFont(destination) as saved:
                coverage = set(saved.getBestCmap())
                # FontTools also retains Unicode mirroring partners needed by
                # shaping (for example '<' with '>'). Only the requested points
                # enter unicode-range, so the CSS faces remain disjoint.
                if not points <= coverage or not coverage <= available:
                    raise ValueError('Font subset coverage changed unexpectedly: '+destination.name)
            css.append(face_rule(family,destination.relative_to(web).as_posix(),weight,points))
            item = {'family':family,'source':relative,'file':destination.relative_to(web).as_posix(),'part':'interface' if index==0 else 'reading','glyphs':len(points),'shapingExtraGlyphs':len(coverage-points),'bytes':destination.stat().st_size,'sourceBytes':len(original)}
            report.append(item)
            print(json.dumps(item,ensure_ascii=False),flush=True)
        remaining = available - set.union(*groups)
        if remaining:
            # Do not advertise U+0-10FFFF: one unsupported symbol would trigger
            # a whole-font download just to discover that its glyph is missing.
            css.append(face_rule(family,relative,weight,remaining))
    destination = web/'auth/theme/fonts-optimized.css'
    temporary = destination.with_suffix('.css.tmp')
    temporary.write_text('\n'.join(css)+'\n')
    temporary.replace(destination)
    return report


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--web',type=Path,default=ROOT/'web')
    parser.add_argument('--report',type=Path)
    args = parser.parse_args()
    result = build(args.web)
    if args.report:
        args.report.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
