'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search),name=params.get('name')||'';
const from=['planner','demons','skills','essences'].includes(params.get('from'))?params.get('from'):'skills';
$('detail-back').href='/?tab='+from;
$('detail-back').onclick=e=>{if(document.referrer.startsWith(location.origin+'/')&&history.length>1){e.preventDefault();history.back();}};
function theme(value){document.documentElement.dataset.theme=value;$('detail-theme').textContent=value==='light'?'深色模式':'浅色模式';try{localStorage.setItem('smtvv-theme',value);}catch{}}
try{theme(localStorage.getItem('smtvv-theme')||'dark');}catch{theme('dark');}
$('detail-theme').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');
async function load(){try{const response=await fetch('/api/skill?name='+encodeURIComponent(name));const s=await response.json();if(!response.ok)throw Error(s.error||'没有找到该技能');document.title=s.label+' · 技能详情 · 真女5复仇';
$('skill-detail').innerHTML=`<div class="detail-title"><div><div class="eyebrow">SKILL DETAILS</div><h1>${esc(s.label)}</h1><p>${esc(s.name)}</p></div><span class="tag ${s.unique?'warning':''}">${esc(s.restriction)}</span></div><div class="detail-facts"><div><small>技能类别</small><strong>${esc(s.categoryZh)}</strong></div><div><small>作用对象</small><strong>${esc(s.targetZh)}</strong></div><div><small>基础消耗</small><strong>${esc(s.costZh)}</strong></div></div><section class="detail-effect"><h2>技能效果</h2><p>${esc(s.effectZh)}</p>${s.detailZh?`<div class="detail-numbers">${esc(s.detailZh)}</div>`:''}</section><div class="detail-source-grid"><section><div class="section-heading"><h2>习得仲魔</h2><span class="muted">${s.demons.length} 个来源</span></div><div class="detail-sources">${s.demons.length?s.demons.map(d=>`<a class="detail-source-item" href="/?tab=demons&q=${encodeURIComponent(d.name)}"><strong>${esc(d.label)}</strong><span>${esc(d.race)} · ${d.initial?'初始自带':'Lv.'+d.level+' 习得'}</span>${d.unlock?`<small>${esc(d.unlock)}</small>`:''}</a>`).join(''):'<p class="muted">没有普通仲魔习得来源，请查看下方对应灵体与使用限制。</p>'}</div></section><section><div class="section-heading"><h2>包含该技能的灵体</h2><span class="muted">${s.essences.length} 个来源</span></div><div class="detail-sources">${s.essences.length?s.essences.map(e=>`<a class="detail-source-item" href="/?tab=essences&q=${encodeURIComponent(e.name)}"><strong>${esc(e.label)}</strong><span>${e.transferable?'可转授给仲魔':esc(e.restriction)}</span></a>`).join(''):'<p class="muted">当前资料未记录对应灵体。</p>'}</div></section></div><p class="muted detail-data-note">消耗和数值为基础数据，实际效果受适合度等因素影响。中文效果为按游戏术语整理的译注。资料版本 ${esc(s.version)}。</p>`;
}catch(e){$('skill-detail').innerHTML=`<h1>无法打开技能详情</h1><p class="error">${esc(e.message)}</p><a href="/?tab=skills">返回技能资料</a>`;}}
load();
